from setuptools import find_packages, setup

setup(
    name="brise_plandok",
    version="0.1",
    description="Tools for the text documents of the Vienna Zoning Plan built in the BRISE project",  # noqa
    url="http://github.com/recski/brise-nlp",
    author="Gabor Recski, Adam Kovacs",
    author_email="gabor.recski@tuwien.ac.at",
    license="tbd",
    install_requires=[
        "black==21.12b0",
        "click<8.0",
        "flask",
        "flake8",
        "graphviz",
        "imodels",
        "logging_json",
        "networkx",
        "nltk",
        "numberpartitioning",
        "numpy",
        "openpyxl",
        "pandas",
        "pre-commit",
        "protobuf<=3.20",
        "pydot",
        "simplejson",
        "sklearn",
        "spacy>=2.3.0",
        "streamlit==1.3.1",
        "torch",
        "transformers",
        "tuw-nlp",
        "xpotato==0.1.3",
    ],
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
)
