NOT = "NOT"

ALL_LABELS_SORTED = {
    "Planzeichen": 1844,
    "Widmung": 641,
    "VerkehrsflaecheID": 400,
    "AnordnungGaertnerischeAusgestaltung": 292,
    "Dachart": 282,
    "AnFluchtlinie": 276,
    "VorkehrungBepflanzung": 274,
    "GebaeudeHoeheArt": 242,
    "BegruenungDach": 220,
    "WidmungInMehrerenEbenen": 219,
    "AbschlussDachMaxBezugGebaeude": 219,
    "BBAllgemein": 217,
    "ErrichtungGebaeude": 213,
    "GehsteigbreiteMin": 207,
    "GebaeudeHoeheMaxAbsolut": 200,
    "GesamtePlangebiet": 189,
    "StrassenbreiteMin": 177,
    "GebaeudeBautyp": 175,
    "Nutzungsart": 157,
    "UnterbrechungGeschlosseneBauweise": 154,
    "AufbautenZulaessig": 152,
    "VonBebauungFreizuhalten": 144,
    "DachneigungMax": 132,
    "Bauklasse": 116,
    "EinfriedungAusgestaltung": 115,
    "DurchgangBreite": 109,
    "BebauteFlaecheMaxProzentual": 107,
    "AusnahmeGaertnerischAuszugestaltende": 103,
    "StrassenbreiteMax": 100,
    "BauweiseID": 97,
    "DurchgangHoehe": 96,
    "VolumenUndUmbaubarerRaum": 91,
    "UnterirdischeBaulichkeiten": 85,
    "Struktureinheit": 81,
    "Stockwerk": 80,
    "EinfriedungHoeheGesamt": 77,
    "DachflaecheMin": 71,
    "BebauteFlaecheMax": 69,
    "VerbotFensterZuOeffentlichenVerkehrsflaechen": 67,
    "BebauteFlaecheMaxNebengebaeude": 65,
    "VorstehendeBauelementeAusladungMax": 61,
    "VerbotWohnung": 61,
    "EinfriedungLage": 56,
    "AnOeffentlichenVerkehrsflaechen": 54,
    "OeffentlicheVerkehrsflaecheBreiteMin": 51,
    "AnordnungGaertnerischeAusgestaltungProzentual": 50,
    "StrassenbreiteVonBis": 49,
    "EinfriedungZulaessig": 48,
    "BebauteFlaecheMin": 48,
    "VorbautenVerbot": 46,
    "AnlageZumEinstellenVorhanden": 44,
    "EinleitungNiederschlagswaesser": 36,
    "AnteilDachbegruenung": 36,
    "VerbotStaffelung": 32,
    "GebaeudeHoeheMaxWN": 32,
    "StellplatzImNiveauZulaessig": 27,
    "ArkadeHoehe": 27,
    "FBOKMinimumWohnungen": 20,
    "MaxAnzahlGeschosseOberirdisch": 19,
    "AnzahlGebaeudeMax": 19,
    "StellplatzregulativUmfangMinimumRelativ": 18,
    "InSchutzzone": 18,
    "Massengliederung": 17,
    "BauklasseVIHoeheMax": 16,
    "StellplatzMax": 15,
    "BauklasseVIHoeheMin": 14,
    "AbschlussDachMaxBezugGelaende": 14,
    "Kleinhaeuser": 13,
    "DachneigungMin": 13,
    "TechnischeAufbautenHoeheMax": 11,
    "StellplatzregulativUmfangMaximumRelativ": 11,
    "OberflaecheBestimmungP": 11,
    "MaxAnzahlDachgeschosse": 11,
    "DurchfahrtHoehe": 11,
    "VorbautenBeschraenkung": 10,
    "VerbotBueroGeschaeftsgebaeude": 10,
    "GaragengebaeudeAusfuehrung": 9,
    "StellplatzregulativUmfangMaximumAbsolut": 8,
    "GebaeudeHoeheMin": 8,
    "MindestraumhoeheEG": 7,
    "BestimmmungenFuerHochhausUndGrossbauvorhaben": 7,
    "HoehenlageGrundflaeche": 6,
    "Geschaeftsstrassen": 6,
    "DurchfahrtBreite": 6,
    "GebaeudeEinschraenkungP": 5,
    "AusnahmeVonWohnungenUnzulaessig": 5,
    "HochhausZulaessigGemaessBB": 4,
    "MaxAnzahlGeschosseOberirdischOhneDachgeschoss": 3,
    "ZulaessigeGeschossanzahlEinkaufszentrum": 2,
    "Einbautrasse": 2,
    "VerbotStellplaetzeUndParkgebaeude": 1,
    "VerbotAufenthaltsraum": 1,
    "AnteilBaumbepflanzung": 1,
}

RULE_BASED_ATTRIBUTES = [
    "AbschlussDachMaxBezugGebaeude",
    "AnFluchtlinie",
    "AnOeffentlichenVerkehrsflaechen",
    "AnordnungGaertnerischeAusgestaltung",
    "AnordnungGaertnerischeAusgestaltungProzentual",
    "AnteilDachbegruenung",
    "AufbautenZulaessig",
    "AusnahmeGaertnerischAuszugestaltende",
    "BBAllgemein",
    "BauweiseID",
    "BebauteFlaecheMax",
    "BebauteFlaecheMaxNebengebaeude",
    "BebauteFlaecheMaxProzentual",
    "BebauteFlaecheMin",
    "BegruenungDach",
    "Dachart",
    "DachflaecheMin",
    "DachneigungMax",
    "DurchgangBreite",
    "DurchgangHoehe",
    "FBOKMinimumWohnungen",
    "GebaeudeBautyp",
    "GebaeudeHoeheArt",
    "GebaeudeHoeheMaxAbsolut",
    "GebaeudeHoeheMaxWN",
    "GehsteigbreiteMin",
    "Nutzungsart",
    "OeffentlicheVerkehrsflaecheBreiteMin",
    "Planzeichen",
    "StellplatzregulativUmfangMaximumRelativ",
    "StellplatzregulativUmfangMinimumRelativ",
    "Stockwerk",
    "UnterbrechungGeschlosseneBauweise",
    "VerbotFensterZuOeffentlichenVerkehrsflaechen",
    "VerbotWohnung",
    "VolumenUndUmbaubarerRaum",
    "VonBebauungFreizuhalten",
    "VorkehrungBepflanzung",
    "Widmung",
    "WidmungInMehrerenEbenen",
]

RANDOM_STATE = 42
TOP = 40
MAX_DEPTH = 5
MIN_FREQ = 50
